#! /usr/bin/env bash
# vim: ft=bash

# hide - each parameter is treated as a path to a filesystem object.
# Each fso is moved from <name> to .<name>


while [[ -n "$1" ]]; do
    # Check for existence
    if [[ -e  "$1" ]]; then
        # More tests needed, but this will do for now 2023-05-19
        echo mv "$1" ".$1"
        mv "$1" ".$1"
    else
        1>&2 echo "\"$1\" does not exist. It failed [[ -e \"$1\" ]]"
    fi
    shift
done
