#! /usr/bin/dash
# vim: ft=bash

# rysnc with Dan's desired options
exec rsync       \
    --quiet      \
    --archive    \
    --acls       \
    --xattrs     \
    --atimes     \
    --crtimes    \
    --hard-links \
    --delete     \
    "$@"

